version: "3"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
