version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - MYSQL_HOST=db
      - MYSQL_USER=newuser
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=auth_service_db
      - EMAIL_USER=preciousdpb2000@gmail.com
      - EMAIL_PASS=NULL
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Dumka0510
      MYSQL_DATABASE: auth_service_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
